### ISSUE TITLE
Grafana Dashboard is empty

### ISSUE THREAD

**Issue by skorpion1298** [avojak/pihole-influxdb-monitor#1]
Hello,

I have added your Grafana Dashboard JSON into my Grafana but all of the Panels are emtpy.
What am I missing?

Thank you!

**Comment by avojak** [comment]
My guess is that you'll have to modify the queries for the panels to use the right alias assigned to your Pi-hole instance(s). That JSON file is just an export of the one I use at home, so all the queries use naming like 'pihole-01' and 'pihole-02'.  I'm not really sure the right way to make a Grafana template.
