### ISSUE TITLE
Null value for query count

### ISSUE THREAD

**Issue by dlmorgan999** [avojak/pihole-influxdb-monitor#10]
I just noticed that the three "top" panels are displaying _null_ for the query count.   Here's a screenshot for "Top Ads", but all three panels are behaving the same way:

<img width="221" alt="image" src="https://github.com/avojak/pihole-influxdb-monitor/assets/7689947/95a59d8b-fbfc-48fe-907b-b6fd333dc0a3">

Compared to this from the Pi-hole web page:

<img width="349" alt="image" src="https://github.com/avojak/pihole-influxdb-monitor/assets/7689947/ba73216d-b01f-4b8e-8920-e2fee66e0e65">

**Comment by avojak** [comment]
Looks like the same issue as #9

**Comment by avojak** [comment]
@dlmorgan999 If you're able to provide the same debug output requested over on #9 that'd be really helpful!
