### ISSUE TITLE
Grafana Dashboard shows nothing

### ISSUE THREAD

**Issue by feloxxx** [avojak/pihole-influxdb-monitor#11]
I found your great project on GitHub and would like to use it in my field. I use the Phyton script which writes cleanly to the data in an InfluxDB. That's where I see the data. The Garfana InfluxDB connection also works. But in the dashboard from the Git here, no data arrives. I find no error....

So I'll just ask. Best regards, Felix
![Screenshot 2024-03-27 103911](https://github.com/avojak/pihole-influxdb-monitor/assets/67307325/e547d3df-3d9f-4859-9fd6-aa38ba390faa)

![Screenshot 2024-03-27 120740](https://github.com/avojak/pihole-influxdb-monitor/assets/67307325/6166daa3-5380-45bd-856d-e90caac5f632)

![Screenshot 2024-03-27 120831](https://github.com/avojak/pihole-influxdb-monitor/assets/67307325/7405b769-3ca8-4938-932f-fe476bf4edb0)

**Comment by avojak** [comment]
Hey, thanks for the interest in the project! I've never seen those error indicators in Grafana before, are there any errors in the Grafana logs? I did a brief search and found someone reporting a similar issue: https://community.grafana.com/t/public-dashboard-internal-server-error/105423

Are you able to see any data if you try to create a new dashboard from scratch (instead of using the one in the repo) with just one panel to pull some data from the InfluxDB bucket?

**Comment by feloxxx** [comment]
Hi Avojak, thank you very much for your quick response. Unfortunately, I am not able to create my own dashboard or anything else in Grafana. I'm just a simple private user who has fun with technology. If you send me a small test dashboard, I'll be happy to give it a try. I would be very happy! Thank you Dnak in advance!

**Comment by avojak** [comment]
Something else that I just thought of is that the dashboard JSON declares some input variables (the `__inputs` section at the very top of the file). I recently learned that these inputs are only supported when importing via the UI (for example, it'll prompt you to select the InfluxDB datasource from the list of configured data sources). If you instead simply drop in the JSON file to the hot-reload directory for dashboards, you'll see similar errors (in which case you'd have to manually edit the JSON to replace all the `${DS_INFLUXDB_PIHOLE}` references with the actual value of the InfluxDB data source). Hope that helps!
