### ISSUE TITLE
Influx error

### ISSUE THREAD

**Issue by sahara101** [avojak/pihole-influxdb-monitor#15]
Hey, 

can you help with this error?

`11:18:47 [INFO] [pihole] Queried successfully in 32ms
11:18:47 [ERROR] Error writing data to InfluxDB: (422)
Reason: Unprocessable Entity
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json; charset=utf-8', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Version': 'v2.7.10', 'X-Platform-Error-Code': 'unprocessable entity', 'Date': 'Tue, 03 Sep 2024 11:18:47 GMT', 'Content-Length': '221'})
HTTP response body: {"code":"unprocessable entity","message":"failure writing points to database: partial write: field type conflict: input field \"NS\" on measurement \"query_types\" is type integer, already exists as type float dropped=1"}`

I assume it is the Query Types as that one is the only empty one 

<img width="1303" alt="image" src="https://github.com/user-attachments/assets/665f8bd6-bb00-49e6-8bb3-c8b4ba242951">

Thanks!

**Comment by c3p0vsr2d2** [comment]
Same error on my side - any resolution to this ?

**Comment by avojak** [comment]
Started working on this a few weeks a go right before leaving for a vacation, but I'm back now so should be fixed soon! 😄 A similar fix has already been merged (but not yet released) for the forward_destinations: https://github.com/avojak/pihole-influxdb-monitor/pull/16/files#diff-69b6c7ed66e07a936372e7db1f3cea5d2f83ebcb145a7a47bdd1565c4690a7d2

**Comment by c3p0vsr2d2** [comment]
thanks avojak, will wait for the fix.

**Comment by avojak** [comment]
Should be fixed with this commit: https://github.com/avojak/pihole-influxdb-monitor/commit/740e07f619d8f46b0c0824cde5b3c7ca1c7598ef

Will be publishing a release soon. You may need to either drop the InfluxDB bucket, or make a manual modification to set the field type for existing values (not sure how to do that).

**Comment by avojak** [comment]
Fixed in 1.4.0 release

**Comment by c3p0vsr2d2** [comment]
works after database delete, thank you!
