### ISSUE TITLE
No support to Raspi or ARM systems

### ISSUE THREAD

**Issue by james-gonzalez** [avojak/pihole-influxdb-monitor#4]
The docker image avojak/pihole-influxdb 

There is no ARM version of this Docker image

Something I can help with?

```bash
# docker run -it avojak/pihole-influxdb bash
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v8) and no specific platform was requested
exec /usr/local/bin/python: exec format error
```

**Comment by avojak** [comment]
Great suggestion! I'll look into it

**Comment by avojak** [comment]
Support added with the 1.2.0 release: https://github.com/avojak/pihole-influxdb-monitor/releases/tag/1.2.0

<img width="1213" alt="Screenshot 2023-07-04 at 10 53 57 AM" src="https://github.com/avojak/pihole-influxdb-monitor/assets/3663899/2b8d3f08-197c-4182-b84b-eee52730801c">
