### ISSUE TITLE
[Request] Top 10 to Top XX

### ISSUE THREAD

**Issue by c3p0vsr2d2** [avojak/pihole-influxdb-monitor#6]
For the docker container, could we get an environment variable to increase the top 10 queries/ads/etc in the code to something else, like top 20 or top 50? Seems that there are only 4 locations in pihole-influxdb.py that need to be changed (I am unfortunately not familiar enough to modify the code to propagate the env variable to the python file)

**Comment by avojak** [comment]
https://github.com/avojak/pihole-influxdb-monitor/commit/531ac4c402ef22a1ca52458882c9a24423377af5

**Comment by avojak** [comment]
Added in version [1.3.0](https://github.com/avojak/pihole-influxdb-monitor/releases/tag/1.3.0)

**Comment by c3p0vsr2d2** [comment]
whoa, thank you avojak, much appreciated~

**Comment by avojak** [comment]
Of course! Caught me right as I was about to sit down at my desk to work on some projects 😆
