### ISSUE TITLE
Grafana pi-hole query data = null

### ISSUE THREAD

**Issue by golvellius** [avojak/pihole-influxdb-monitor#9]
Hi ..
I would like to thanks you about this great pihole monitor docker. I have been using for 1 week and all is working, but i have a small problem, on query data i have always null value .. 
![image](https://github.com/avojak/pihole-influxdb-monitor/assets/17733658/6309e402-606c-40b9-85ec-39fdebbedfad)

This is my pihole versions:
Docker:2024.01.0 
Pi-Hole:5.17.3
FTL:5.24
WebInter:5.21.

Thanks.

**Comment by avojak** [comment]
Are there any errors in the logs? And could you try running with the environment variable `DEBUG=true` and providing a small sample of the log output? It should log out the data retrieved from the Pi-hole before sending to InfluxDB - that'll help me narrow things down a bit. I'm not currently able to reproduce the issue with my setup.

**Comment by Jh123x** [comment]
![image](https://github.com/avojak/pihole-influxdb-monitor/assets/10459011/79df347a-5771-4e10-a26b-76bb38a7bdca)
Not sure if this helps, but this is the data shape

**Comment by Jh123x** [comment]
![image](https://github.com/avojak/pihole-influxdb-monitor/assets/10459011/79dd1592-973c-415b-a767-d1fcd7a42153)

Seems like changing the transform for the dashboard to this solves the issue

**Comment by avojak** [comment]
@Jh123x Thanks for the data! I'll need to check out the code more closely, but I wonder if I'm not properly ensuring that the data is sent as the right type...

**Comment by avojak** [comment]
Fixed with this commit: https://github.com/avojak/pihole-influxdb-monitor/commit/409286ae6a28e126c7dd79d4c27349f9f95c22e5

**Comment by avojak** [comment]
Fixed in 1.4.0 release
